# Dependabot configuration for ON1Builder
version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    allow:
      - dependency-type: "direct"
    assignees:
      - "John0n1"
      - "denibur"
      - "Soljuan"
    reviewers:
      - "John0n1"
      - "denibur"
      - "Soljuan"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
      include: "scope"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    versioning-strategy: "auto"
    groups:
      python-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"

