# Dependabot - ON1Builder
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    allow:
      - dependency-name: "*"
        dependency-type: "direct"
    assignees:
      - "John0n1"
      - "soljuan"
      - "denibur"

    reviewers:
      - "John0n1"
      - "soljuan"
      - "denibur"

    commit-message:
      prefix: "chore: "
      prefix-development: "chore(dev): "
      include: "scope"
    open-pull-requests-limit: 8
    rebase-strategy: "auto"
    versioning-strategy: "increase-if-necessary"
    milestone: 1
    groups:
      core:
        patterns:
          - "django"
        update-types:
          - "minor"
          - "patch"
