name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '⚙️ Dependencies'
    labels:
      - 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'bugfix'
      - 'fix'
      - 'maintenance'
      - 'docs'
      - 'documentation'
      - 'dependencies'
  default: patch
template: |
  ## ON1Builder $RESOLVED_VERSION
  
  $CHANGES
  
  **Full Changelog**: https://github.com/john0n1/ON1Builder/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
  
  ## Installation
  
  ```bash
  pip install on1builder==$RESOLVED_VERSION
  ```
  
  Or with Poetry:
  
  ```bash
  poetry add on1builder==$RESOLVED_VERSION
  ```
