version: '3.8'

services:
  on1builder:
    build: .
    container_name: on1builder
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./configs:/app/configs
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000"
    command: python ignition.py
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: on1builder-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: on1builder-postgres
    environment:
      POSTGRES_DB: on1builder
      POSTGRES_USER: on1builder
      POSTGRES_PASSWORD: on1builder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
